### ISSUE TITLE
Error creating tab

### ISSUE THREAD

**Issue by Moosems** [muhammeteminturgut/ttkScrollableNotebook#4]
When I create a tab it gives the error:
```
Traceback (most recent call last):
  File "/Users/joshyacktman/Documents/PyApps/Working/JDE/test2.py", line 155, in <module>
    notebook.add(text_piece, text="Untitled")
  File "/Users/joshyacktman/Documents/PyApps/Working/JDE/ttkScrollableNotebook.py", line 67, in add
    if len(self.notebookTab.winfo_children())!=0:
AttributeError: 'CustomNotebook' object has no attribute 'notebookTab'
```

What should I do?

**Comment by lopuma** [comment]
check my code, it's in spanish, I hope it helps you

[ScrollableNotebook](https://github.com/lopuma/APP-COMPLIANCE/blob/scripts/ScrollableNotebook.py)
